### ISSUE TITLE
About the hyperparameter

### ISSUE THREAD

**Issue by KeepYang** [ChandlerBang/Pro-GNN#11]
Really wonderful work, thank you for your contribution! Recently I'm trying to reproduce the results in your paper using deeprobust, but it seems that the default hyperparameters could not directly get the best result. Could you provide the elaborate hyperparameters for running? I will be grateful for your help!

**Comment by ChandlerBang** [comment]
Hi, for the hyper-parameters of Pro-GNN please check https://github.com/ChandlerBang/Pro-GNN/tree/master/scripts/meta

**Comment by KeepYang** [comment]
> Hi, for the hyper-parameters of Pro-GNN please check https://github.com/ChandlerBang/Pro-GNN/tree/master/scripts/meta

Nice, thank you so much!
