### ISSUE TITLE
A question about generating nettacked data

### ISSUE THREAD

**Issue by ocrinz** [ChandlerBang/Pro-GNN#13]
Hi,

Really nice work!  I've got a question about how to generate the nettacked data (in the `nettack` folder of this repo).  In this folder, only one perturbed adj is provided for each graph under each ptb_rate.  It seems that each perturbed adj is attacked for all target nodes.  

However, the argument `target_node` of `Nettack.attack` in DeepRobust is only a single node.  I have no idea how to pass all target nodes to Nettack simultaneously.  I can't find related details in the paper, either.  So I'm a bit confused how the nettacked data were generated.  

In fact I'm trying to apply nettack on other graphs but can't figure out how to. So it would be very helpful if you could provide some details about how you generated these nettacked data.  

Thanks!

**Comment by ChandlerBang** [comment]
Hi,

Thanks for your interest in our work. It is true that the argument `target_node` of `Nettack.attack` in DeepRobust is only a single node. It does not support "attacking all target nodes simultaneously".  

In the setting of Pro-GNN, we first select the target nodes to be attacked and then perform Nettack **sequentially**, i.e., attack the nodes one by one. In this case, there will only be **one** attacked graph.

You can also try the setting of the **Nettack** paper, which test each target node separately (there will be K attacked graphs if you have K target nodes). You may check our example code [here](https://github.com/DSE-MSU/DeepRobust/blob/master/examples/graph/test_nettack.py).

**Comment by ocrinz** [comment]
Thanks for your timely reply!  Now it is a lot more clear.
