### ISSUE TITLE
About pubmed dataset 

### ISSUE THREAD

**Issue by songshuhan** [ChandlerBang/Pro-GNN#15]
Hi，Thank you so much for sharing the code，However, when I run large data sets such as PubMed, there will be a problem of insufficient CUDA memory,How did you solve it？

**Comment by ChandlerBang** [comment]
Hi, 

Pro-GNN needs to learn a dense adjacency matrix which requires large GPU memory just as attacking the adjacency matrix. You may refer to https://github.com/ChandlerBang/Pro-GNN/issues/7.
