### ISSUE TITLE
about the details of the metattack experiment

### ISSUE THREAD

**Issue by shumanzhuang** [ChandlerBang/Pro-GNN#21]
Hi~thanks for sharing the code! I would like to ask a question related to the metattack experiment. 
In subsection 5.3 you investigate the weights of normal and adversarial edges in the learned adjacency matrix S. How can we obtain which edges are normal and which are adversarial in the adjacency matrix? I don't find a key for adversarial edges in the properties of meta datasets, or am I missing it?
I'm doing experiments with the meta datasets, but I'm troubled by this question, I would appreciate it if you could reply！

**Comment by ChandlerBang** [comment]
Thank you for your interest in our work. We have the adjacency matrices for both the attacked graph and clean graph, say A1 and A2. You can simply obtain the adversarial edges by subtracting them, i.e., A1 - A2.

**Comment by shumanzhuang** [comment]
I get it, thanks a lot!
