### ISSUE TITLE
Code for training using GAT

### ISSUE THREAD

**Issue by vailatuts** [ChandlerBang/Pro-GNN#3]
Thanks for your wonderful work, I am wondering if the code for training using GATs could be provided? 

Regards

**Comment by ChandlerBang** [comment]
Hi, thanks for your interest in your work. Currently I am occupied with some research projects and not available to implement that. I might consider it in the future. You can also try to implement it by yourself. It would be not hard to change the code to use GAT as we only need to replace GCN with GAT.

**Comment by vailatuts** [comment]
Thanks!
