### ISSUE TITLE
How to compute the rank of adjacency maxtrix

### ISSUE THREAD

**Issue by PatPathead** [ChandlerBang/Pro-GNN#6]
Hi, I have a question about the computation of the rank of adjacency. I see the paper says the rank of perturbated adjacency matrix will become larger. However, when I use torch.matrix_rank() to compute the rank, I find they are the same. 

So do they use another function or preprocess the adjacency matrix? Thanks!

**Comment by ChandlerBang** [comment]
Hi, you can do as follows to calculate the relative growth rate
```
rank1 = np.linalg.matrix_rank(unprocessed_adj)
rank2 = np.linalg.matrix_rank(unprocessed_perturbed_adj)
rate = (rank2 - rank1) / rank1 * 100
```
