### ISSUE TITLE
GPU OOM on Pubmed

### ISSUE THREAD

**Issue by Chenhui1016** [ChandlerBang/Pro-GNN#7]
Hi,

It seems that we have to use a dense "perturbed_adj" for "prognn.fit()"? I'm currently facing an out-of-memory issue on GPU when running the script on Pubmed dataset (both Cora and Citeseer work to me). I guess the dense adjacency matrix for Pubmed would consume lots of GPU memory and thus cause OOM (My GPU has around 10G memory)? Running the script on CPU would be too slow. Any solutions to solve this? Thanks in advance.

**Comment by ChandlerBang** [comment]
Yes, that is true. ProGNN can only deal with the dense matrix as it needs to perform SVD and reconstruct the adjacency matrix. I used a GPU with 32GB and it worked well on Pubmed dataset. This is actually the major drawback of this model, which can be considered as a future work to improve.  Also it is worth noting that metattack consumes even more than 32 GB memory on Pubmed.
